#!/usr/bin/env python
import csv
import datetime
import decimal

import psycopg2
from ihazmoney import wire_db


db = wire_db()


transactions = csv.reader(open('transactions.csv'))
headers = transactions.next()
balance = 0
for row in transactions:
    email = "admin@ihazmoney.com"
    month, day, year = [int(x) for x in row[0].split('/')]
    date = datetime.date(year, month, day)
    amount = decimal.Decimal(row[3])
    assert row[4] in ['credit', 'debit']
    if row[4] == 'debit':
        amount *= -1
    description = row[2]

    balance += amount
    print balance
    
    try:
        db.execute("""
        
            INSERT INTO transactions (email, date, amount, description)
                 VALUES (%s, %s, %s, %s);
            UPDATE users SET balance = ((
                SELECT balance FROM users WHERE email = %s
            ) + %s) WHERE email = %s

        """, ( email, date, amount, description
             , email, amount, email
              ))
    except psycopg2.IntegrityError:
        print "dupe:", email, date, amount, description
