#!/usr/bin/env python
"""Run a command with an environment specified in a file.
"""
import os, sys

if len(sys.argv) < 2:
    m ="[SWADDLE] Usage: %s {definition.env} {command} {args}" % sys.argv[0]
    raise SystemExit(m)

envdef = sys.argv[1]
if not os.path.isfile(envdef):
    m = "[SWADDLE] %s is not a file; environment unchanged." % envdef
    print >> sys.stderr, m
    envdef = ""

args = sys.argv[2:]
if not args:
    m ="[SWADDLE] No command specified; exiting."
    raise SystemExit(m)
if not os.path.isfile(args[0]):
    m ="[SWADDLE] Command %s does not exist; exiting." % args[0]
    raise SystemExit(m)

if envdef:
    fp = open(envdef)
    for line in fp:
        line = line.strip()
        if "=" not in line:
            m = "[SWADDLE] Skipping line: %s." % line
            print >> sys.stderr, m
        key, val = line.split("=", 1)
        os.environ[key] = val

os.execv(args[0], args)
